// Builds index.html, the people kit sheet. Run: node build.mjs
import { CAST, bust, avatar } from './cast.mjs';
import { writeFileSync } from 'node:fs';

const SH = `<filter id="sh" x="-20%" y="-20%" width="140%" height="170%"><feDropShadow dx="0" dy="6" stdDeviation="7" flood-color="#131B22" flood-opacity=".13"/></filter>`;
const say = (x,y,lines,size=19)=>lines.map((l,i)=>`<text class="say" x="${x}" y="${y+i*(size+7)}" font-size="${size}" fill="#222B32">${l}</text>`).join('');
const prep = (x,y,rot=0)=>`<g transform="rotate(${rot} ${x+56} ${y+42})"><rect x="${x}" y="${y}" width="112" height="84" rx="10" fill="#fff" filter="url(#sh)"/><rect x="${x+12}" y="${y+12}" width="40" height="7" rx="3.5" fill="#686E74"/><rect x="${x+12}" y="${y+30}" width="12" height="12" rx="3" fill="#FBF1E0" stroke="#B67118" stroke-width="2"/><rect x="${x+30}" y="${y+32}" width="70" height="8" rx="4" fill="#E3E6E9"/><rect x="${x+12}" y="${y+52}" width="88" height="7" rx="3.5" fill="#E3E6E9"/><rect x="${x+12}" y="${y+66}" width="60" height="7" rx="3.5" fill="#E3E6E9"/></g>`;

// Cast sheet
const people = Object.values(CAST);
const castSvg = people.map((p,i)=>`<figure class="c"><svg viewBox="-60 -50 120 150"><defs><clipPath id="cc${i}"><rect x="-60" y="-50" width="120" height="150" rx="14"/></clipPath></defs><rect x="-60" y="-50" width="120" height="150" rx="14" fill="#EEF2F4"/><g clip-path="url(#cc${i})">${bust(p,{y:4})}</g></svg><figcaption>${p.name}</figcaption></figure>`).join('');

// A · across the table
const A = `<svg viewBox="0 0 600 380">${'<defs>'+SH+'</defs>'}
<rect x="150" y="30" width="300" height="80" rx="16" fill="#fff" filter="url(#sh)"/><path d="M196 108 l-6 22 l24 -22z" fill="#fff"/>
${say(172,63,['Where did Brightline land?','I still owe you that intro.'])}
${bust(CAST.you,{x:170,y:176,s:1.3,h:90})}
${bust(CAST.maya,{x:430,y:176,s:1.3,h:90})}
<rect x="96" y="268" width="408" height="112" rx="10" fill="#E6EBEE"/>
<rect x="80" y="252" width="440" height="20" rx="10" fill="#fff" filter="url(#sh)"/>
<rect x="186" y="240" width="74" height="17" rx="8.5" fill="#066A65"/>
<rect x="340" y="240" width="74" height="17" rx="8.5" fill="#4C5380"/>
<g transform="translate(236 200) scale(.62)">${prep(0,0,-5)}</g>
</svg>`;

// B · on a call
const tile=(x,bg,p,label,dot)=>`<clipPath id="t${x}"><rect x="${x}" y="36" width="252" height="184" rx="16"/></clipPath><rect x="${x}" y="36" width="252" height="184" rx="16" fill="${bg}" filter="url(#sh)"/><g clip-path="url(#t${x})">${bust(p,{x:x+126,y:118,s:1.25,h:120})}</g><rect x="${x+12}" y="188" width="${label.length*7.4+30}" height="22" rx="11" fill="#fff"/><circle cx="${x+24}" cy="199" r="5" fill="${dot}"/><text x="${x+34}" y="204" font-size="12" font-weight="600" fill="#222B32">${label}</text>`;
const B = `<svg viewBox="0 0 600 380"><defs>${SH}</defs>
${tile(36,'#E4EEEC',CAST.you,'You','#087E78')}${tile(312,'#E7E8F1',CAST.maya,'Maya Reyes','#C9CDD0')}
<rect x="96" y="252" width="330" height="80" rx="16" fill="#fff" filter="url(#sh)"/><path d="M150 254 l6 -22 l20 22z" fill="#fff"/>
${say(118,285,['Where did Brightline land?','I still owe you that intro.'])}
${prep(452,250,4)}
</svg>`;

// C · as a conversation
const C = `<svg viewBox="0 0 600 380"><defs>${SH}</defs>
${avatar(CAST.you,{x:96,y:140,r:46,bg:'#E4EEEC'})}
${avatar(CAST.maya,{x:504,y:236,r:46,bg:'#E7E8F1'})}
<rect x="164" y="98" width="300" height="80" rx="16" fill="#fff" filter="url(#sh)"/><path d="M166 126 l-18 12 l18 8z" fill="#fff"/>
${say(186,131,['Where did Brightline land?','I still owe you that intro.'])}
<rect x="136" y="206" width="300" height="56" rx="16" fill="#fff" filter="url(#sh)"/><path d="M434 226 l18 10 l-18 8z" fill="#fff"/>
${say(158,240,['Still stuck. Their CS lead went quiet.'])}
${prep(40,270,0)}
</svg>`;

const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>People kit · The Same Page</title>
<!-- Generated by build.mjs from cast.mjs. Edit those, not this file. -->
<style>
:root{--canvas:#F5F8FA;--hairline:#DDE0E3;--ink:#222B32;--ink-secondary:#4F575D}
body{margin:0;background:var(--canvas);font-family:system-ui,-apple-system,'Segoe UI',Arial,sans-serif;color:var(--ink)}
.wrap{max-width:1240px;margin:0 auto;padding:36px 40px 56px}
h1{font-size:28px;margin:0 0 6px;letter-spacing:-.02em}h2{font-size:19px;margin:34px 0 4px}
p.i{color:var(--ink-secondary);margin:0 0 18px;font-size:15px;line-height:1.55;max-width:80ch}
.cast{display:grid;grid-template-columns:repeat(9,minmax(0,1fr));gap:12px}
.c{margin:0}.c svg{display:block;width:100%;height:auto}.c figcaption{font-size:12.5px;font-weight:600;margin-top:6px;text-align:center}
.scenes{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}
.s{background:#fff;border:1px solid var(--hairline);border-radius:14px;padding:14px}
.s svg{display:block;width:100%;height:auto;background:var(--canvas);border-radius:10px}
.s h3{font-size:16px;margin:12px 0 4px}.s p{font-size:14px;line-height:1.5;color:var(--ink-secondary);margin:0}
.say{font-family:'Newsreader',Georgia,serif}
ul{font-size:14.5px;line-height:1.6;color:var(--ink-secondary);padding-left:1.2rem;max-width:85ch}
@media (max-width:900px){.cast{grid-template-columns:repeat(3,minmax(0,1fr))}.scenes{grid-template-columns:1fr}}
</style></head><body><div class="wrap">
<h1>People kit</h1>
<p class="i">The one way people are drawn on this site. Faceless, slim, flat, in the site's own colours and shapes. The cast matches the names used in the example data, so the same person looks the same everywhere they appear.</p>
<h2>The cast</h2>
<p class="i">You wear the brand teal; everyone else wears a muted colour of their own. Amber is never clothing, because amber means "still open".</p>
<div class="cast">${castSvg}</div>
<h2>Three scenes to build from</h2>
<p class="i">Pick the scene by the moment, not by variety. Each holds a with and a without version by swapping what's in hand (the prep card) and what's said.</p>
<div class="scenes">
<div class="s">${A}<h3>A · Across the table</h3><p>An in-person 1:1. The most human of the three; use for the headline moment in a section.</p></div>
<div class="s">${B}<h3>B · On a call</h3><p>A remote or hybrid 1:1, which is most of the audience. Name tags carry the ownership dot (teal for you).</p></div>
<div class="s">${C}<h3>C · As a conversation</h3><p>When the words matter more than the room: several lines of an exchange, avatars instead of bodies.</p></div>
</div>
<h2>Rules</h2>
<ul>
<li>Sparingly: only where the moment is between people, chiefly the 1:1. A handful of scenes per page at most.</li>
<li>No faces. Hair, skin tone, glasses, a beard and clothing colour carry the person.</li>
<li>Slim proportions are fixed in cast.mjs (head r22, torso 64 wide). Scale the whole figure, never stretch it.</li>
<li>Speech is set in Newsreader, the page's voice for a person thinking or talking. Product things stay as white surfaces with pills and marks.</li>
<li>New people are added to the cast in cast.mjs with a name, so they stay consistent across pages. Keep the mix of genders, skin tones and hair.</li>
</ul>
</div></body></html>`;
writeFileSync(new URL('./index.html', import.meta.url), html);
console.log('wrote index.html');
